// ─────────────────────────────────────────────
//  CONFIGURATION — edit this section only
// ─────────────────────────────────────────────

// Spotify IDs: map YouTube video ID → Spotify episode ID
// When a new episode goes live on Spotify, add its ID here.
//   How to find it: open.spotify.com/episode/EPISODE_ID ← that part
const spotifyIds = {
  // "YOUTUBE_VIDEO_ID": "SPOTIFY_EPISODE_ID",
  // example:
  // "9CoWP2DazGA": "4rOoJ6Egrf8EKCIDo4yj5g",
};

// Dishes cooked — update this list manually
const dishes = [
  "Dish Name One",
  "Dish Name Two",
  "Dish Name Three",
  "Dish Name Four",
  "Dish Name Five",
  "Dish Name Six"
];

// ─────────────────────────────────────────────
//  Episodes are loaded from episodes.json,
//  which is auto-generated by the GitHub Action.
//  You do not need to edit anything below this line.
// ─────────────────────────────────────────────

// Sample episodes shown when episodes.json is not available
const sampleKitchenEpisodes = [
  { title: "Jerk Chicken & Life Lessons", description: "Breaking down the perfect jerk marinade while we talk about what it means to cook with intention and purpose.", date: "March 15, 2026" },
  { title: "Oxtail Sundays", description: "Low and slow oxtail stew — the kind your grandma made. We're getting into family traditions and why food is the ultimate love language.", date: "March 8, 2026" },
  { title: "The Perfect Curry Goat", description: "Curry goat done right, from seasoning to slow cook. Plus a real conversation about patience in the kitchen and in life.", date: "March 1, 2026" },
  { title: "Mac & Cheese Wars", description: "Baked vs stovetop — we're settling this once and for all. Every family has their version, and we're tasting through the debate.", date: "February 22, 2026" },
  { title: "Plantain Everything", description: "Fried, boiled, mashed — we're doing it all. Exploring how one ingredient connects so many Caribbean and African dishes.", date: "February 15, 2026" },
];

const sampleCouchEpisodes = [
  { title: "Starting Over at 30", description: "What happens when the plan doesn't work out? We sit down with a guest who quit corporate to follow their passion.", date: "March 12, 2026" },
  { title: "Fatherhood & Fried Fish", description: "A real talk about being a present dad, the pressures men face, and why the kitchen became a place of healing.", date: "March 5, 2026" },
  { title: "Mental Health in the Culture", description: "Breaking the stigma — an honest conversation about therapy, vulnerability, and what it takes to actually ask for help.", date: "February 26, 2026" },
  { title: "Hustling vs. Living", description: "Grind culture told us to never stop. But at what cost? We're unpacking burnout, boundaries, and finding balance.", date: "February 19, 2026" },
  { title: "Community Over Competition", description: "Why building together beats building alone. Stories from entrepreneurs who chose collaboration over the solo path.", date: "February 12, 2026" },
];

let kitchenEpisodes = [];
let couchEpisodes   = [];

// ─────────────────────────────────────────────
//  PAGE BUILDER – no need to edit below this line
// ─────────────────────────────────────────────

function validId(id) {
  return id && !id.includes("_ID");
}

const TRUNCATE_LENGTH = 120;

function truncate(text) {
  if (text.length <= TRUNCATE_LENGTH) return { short: text, isTruncated: false };
  return { short: text.slice(0, text.lastIndexOf(" ", TRUNCATE_LENGTH)) + "…", isTruncated: true };
}

// Descriptions are fetched from descriptions.json, which is generated
// automatically by the GitHub Action on every push. No API key needed here.

// All episodes in one flat list so cards can reference them by index
// Populated after episodes.json loads
const allEpisodes = [];

function buildCard(ep, index) {
  const youtube = validId(ep.youtube)
    ? `<div class="card-video">
        <iframe
          src="https://www.youtube.com/embed/${ep.youtube}"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen
        ></iframe>
      </div>`
    : "";

  const spotify = validId(ep.spotify)
    ? `<iframe
        class="card-spotify"
        src="https://open.spotify.com/embed/episode/${ep.spotify}"
        width="100%"
        height="80"
        frameborder="0"
        allowtransparency="true"
        allow="encrypted-media"
      ></iframe>`
    : "";

  const desc = ep.description || "";
  const { short, isTruncated } = truncate(desc);
  const readMore = isTruncated
    ? `<button class="read-more" data-index="${index}">Read more</button>`
    : "";

  return `
    <div class="card" id="card-${index}">
      <h3>${ep.title}</h3>
      <p class="card-desc">${short}${readMore}</p>
      <div class="ep-meta">${ep.date || ""}</div>
      ${spotify}
      ${youtube}
    </div>`;
}

function updateCard(index) {
  const ep = allEpisodes[index];
  const card = document.getElementById(`card-${index}`);
  if (!card) return;
  const descEl = card.querySelector(".card-desc");
  const { short, isTruncated } = truncate(ep.description || "");
  const readMore = isTruncated
    ? `<button class="read-more" data-index="${index}">Read more</button>`
    : "";
  descEl.innerHTML = short + readMore;
  if (ep.date) card.querySelector(".ep-meta").textContent = ep.date;
}

function buildDishList(dishes) {
  return dishes.map(d => `<li>${d}</li>`).join("\n        ");
}

function openModal(ep) {
  document.getElementById("modal-title").textContent = ep.title;
  document.getElementById("modal-meta").textContent = ep.date;
  document.getElementById("modal-description").textContent = ep.description || "";
  document.getElementById("modal-overlay").classList.add("open");
}

function closeModal() {
  document.getElementById("modal-overlay").classList.remove("open");
}

function initCarousel(trackEl, dotsEl) {
  let current = 0;
  const total = trackEl.children.length;
  if (total === 0) return;

  const carousel = trackEl.closest(".carousel");
  const prevBtn = carousel.querySelector(".prev-btn");
  const nextBtn = carousel.querySelector(".next-btn");

  // Determine how many cards are visible based on viewport width
  function getVisible() {
    if (window.innerWidth <= 600) return 1;
    if (window.innerWidth <= 800) return 2;
    if (window.innerWidth <= 1000) return 3;
    if (window.innerWidth <= 1200) return 4;
    return 5;
  }

  function getMaxIndex() {
    return Math.max(0, total - getVisible());
  }

  function buildDots() {
    dotsEl.innerHTML = "";
    const maxIdx = getMaxIndex();
    const dotCount = maxIdx + 1;
    for (let i = 0; i < dotCount; i++) {
      const dot = document.createElement("button");
      dot.className = "dot" + (i === current ? " active" : "");
      dot.setAttribute("aria-label", `Slide ${i + 1}`);
      dot.addEventListener("click", () => goTo(i));
      dotsEl.appendChild(dot);
    }
  }

  function goTo(index) {
    const maxIdx = getMaxIndex();
    current = Math.max(0, Math.min(index, maxIdx));
    const offset = trackEl.children[current].offsetLeft;
    trackEl.style.transform = `translateX(-${offset}px)`;
    dotsEl.querySelectorAll(".dot").forEach((d, i) => {
      d.classList.toggle("active", i === current);
    });
    prevBtn.disabled = current === 0;
    nextBtn.disabled = current === maxIdx;
  }

  prevBtn.addEventListener("click", () => goTo(current - 1));
  nextBtn.addEventListener("click", () => goTo(current + 1));

  // Keyboard navigation on the carousel
  carousel.setAttribute("tabindex", "0");
  carousel.addEventListener("keydown", (e) => {
    if (e.key === "ArrowLeft") { goTo(current - 1); e.preventDefault(); }
    if (e.key === "ArrowRight") { goTo(current + 1); e.preventDefault(); }
  });

  buildDots();
  goTo(0);

  // Rebuild dots on resize so visible count stays accurate
  window.addEventListener("resize", () => {
    buildDots();
    goTo(current);
  });
}

async function loadEpisodes() {
  try {
    const res = await fetch("episodes.json");
    if (!res.ok) throw new Error("episodes.json not found");
    const data = await res.json();

    kitchenEpisodes = data.kitchen || [];
    couchEpisodes   = data.couch   || [];

    // Merge in any Spotify IDs configured above
    [...kitchenEpisodes, ...couchEpisodes].forEach(ep => {
      if (ep.youtube && spotifyIds[ep.youtube]) {
        ep.spotify = spotifyIds[ep.youtube];
      }
    });

  } catch (e) {
    console.warn("Could not load episodes.json — using sample episodes.", e);
  }

  // Fall back to sample episodes when none are loaded
  if (kitchenEpisodes.length === 0) kitchenEpisodes = sampleKitchenEpisodes;
  if (couchEpisodes.length === 0)   couchEpisodes   = sampleCouchEpisodes;

  // Rebuild allEpisodes and render
  allEpisodes.length = 0;
  allEpisodes.push(...kitchenEpisodes, ...couchEpisodes);

  const kitchenTrack = document.getElementById("kitchen-track");
  const couchTrack   = document.getElementById("couch-track");

  kitchenTrack.innerHTML = kitchenEpisodes.map((ep, i) => buildCard(ep, i)).join("");
  couchTrack.innerHTML   = couchEpisodes.map((ep, i) => buildCard(ep, kitchenEpisodes.length + i)).join("");
  const dishListEl = document.getElementById("dish-list");
  if (dishListEl) dishListEl.innerHTML = buildDishList(dishes);

  initCarousel(kitchenTrack, document.getElementById("kitchen-dots"));
  initCarousel(couchTrack,   document.getElementById("couch-dots"));
}

document.getElementById("modal-close").addEventListener("click", closeModal);
document.getElementById("modal-overlay").addEventListener("click", function(e) {
  if (e.target === this) closeModal();
});
document.addEventListener("keydown", function(e) {
  if (e.key === "Escape") closeModal();
});
document.addEventListener("click", function(e) {
  if (e.target.classList.contains("read-more")) {
    openModal(allEpisodes[e.target.dataset.index]);
  }
});

loadEpisodes();
