// ─────────────────────────────────────────────
//  CONFIGURATION — edit this section only
// ─────────────────────────────────────────────

// Spotify IDs: map YouTube video ID → Spotify episode ID
// When a new episode goes live on Spotify, add its ID here.
//   How to find it: open.spotify.com/episode/EPISODE_ID ← that part
const spotifyIds = {
  // "YOUTUBE_VIDEO_ID": "SPOTIFY_EPISODE_ID",
  // example:
  // "9CoWP2DazGA": "4rOoJ6Egrf8EKCIDo4yj5g",
};

// Dishes cooked — update this list manually
const dishes = [
  "Dish Name One",
  "Dish Name Two",
  "Dish Name Three",
  "Dish Name Four",
  "Dish Name Five",
  "Dish Name Six"
];

// ─────────────────────────────────────────────
//  Episodes are loaded from episodes.json,
//  which is auto-generated by the GitHub Action.
//  You do not need to edit anything below this line.
// ─────────────────────────────────────────────

// Sample episodes shown when episodes.json is not available
const sampleKitchenEpisodes = [
  { title: "Jerk Chicken & Life Lessons", description: "Breaking down the perfect jerk marinade while we talk about what it means to cook with intention and purpose.", date: "March 15, 2026" },
  { title: "Oxtail Sundays", description: "Low and slow oxtail stew — the kind your grandma made. We're getting into family traditions and why food is the ultimate love language.", date: "March 8, 2026" },
  { title: "The Perfect Curry Goat", description: "Curry goat done right, from seasoning to slow cook. Plus a real conversation about patience in the kitchen and in life.", date: "March 1, 2026" },
  { title: "Mac & Cheese Wars", description: "Baked vs stovetop — we're settling this once and for all. Every family has their version, and we're tasting through the debate.", date: "February 22, 2026" },
  { title: "Plantain Everything", description: "Fried, boiled, mashed — we're doing it all. Exploring how one ingredient connects so many Caribbean and African dishes.", date: "February 15, 2026" },
];

const sampleCouchEpisodes = [
  { title: "Starting Over at 30", description: "What happens when the plan doesn't work out? We sit down with a guest who quit corporate to follow their passion.", date: "March 12, 2026" },
  { title: "Fatherhood & Fried Fish", description: "A real talk about being a present dad, the pressures men face, and why the kitchen became a place of healing.", date: "March 5, 2026" },
  { title: "Mental Health in the Culture", description: "Breaking the stigma — an honest conversation about therapy, vulnerability, and what it takes to actually ask for help.", date: "February 26, 2026" },
  { title: "Hustling vs. Living", description: "Grind culture told us to never stop. But at what cost? We're unpacking burnout, boundaries, and finding balance.", date: "February 19, 2026" },
  { title: "Community Over Competition", description: "Why building together beats building alone. Stories from entrepreneurs who chose collaboration over the solo path.", date: "February 12, 2026" },
];

let kitchenEpisodes = [];
let couchEpisodes   = [];

// ─────────────────────────────────────────────
//  PAGE BUILDER – no need to edit below this line
// ─────────────────────────────────────────────

function validId(id) {
  return id && !id.includes("_ID");
}

const TRUNCATE_LENGTH = 120;

function truncate(text) {
  if (text.length <= TRUNCATE_LENGTH) return { short: text, isTruncated: false };
  return { short: text.slice(0, text.lastIndexOf(" ", TRUNCATE_LENGTH)) + "…", isTruncated: true };
}

// Descriptions are fetched from descriptions.json, which is generated
// automatically by the GitHub Action on every push. No API key needed here.

// All episodes in one flat list so cards can reference them by index
// Populated after episodes.json loads
const allEpisodes = [];

function parseEpisodeDate(value) {
  const timestamp = Date.parse(value || "");
  return Number.isNaN(timestamp) ? 0 : timestamp;
}

function normalizeDisplayTitle(title) {
  const raw = String(title || "").trim();
  const cleaned = raw
    .replace(/\s*#\S+/g, "")
    .replace(/\s{2,}/g, " ")
    .trim();

  if (!cleaned) return cleaned;

  const letters = cleaned.replace(/[^A-Za-z]/g, "");
  const uppercaseCount = (letters.match(/[A-Z]/g) || []).length;
  const lowercaseCount = (letters.match(/[a-z]/g) || []).length;
  const looksShouty = uppercaseCount > 8 && uppercaseCount > lowercaseCount * 3;

  if (!looksShouty) return cleaned;

  return cleaned
    .toLowerCase()
    .replace(/(^|[\s([{\-+/:"])([a-z])/g, (_, lead, char) => `${lead}${char.toUpperCase()}`)
    .replace(/\bW\/\b/g, "w/")
    .replace(/\bIi\b/g, "II")
    .replace(/\bIii\b/g, "III")
    .replace(/\bIv\b/g, "IV")
    .replace(/\bVi\b/g, "VI")
    .replace(/\bVii\b/g, "VII")
    .replace(/\bViii\b/g, "VIII");
}

function buildCard(ep, index) {
  const displayTitle = normalizeDisplayTitle(ep.title);
  const metaMarkup = ep.date ? `<p class="card-date">${ep.date}</p>` : "";

  const youtube = validId(ep.youtube)
    ? `<div class="card-video" data-yt="${ep.youtube}">
        <img src="https://img.youtube.com/vi/${ep.youtube}/hqdefault.jpg" alt="${displayTitle}" loading="lazy" />
        <button class="play-btn" aria-label="Play video">
          <svg viewBox="0 0 68 48" width="68" height="48"><path d="M66.5 7.7c-.8-2.9-2.5-5.4-5.4-6.2C55.8.1 34 0 34 0S12.2.1 6.9 1.5c-2.9.8-4.6 3.3-5.4 6.2C.1 13 0 24 0 24s.1 11 1.5 16.3c.8 2.9 2.5 5.4 5.4 6.2C12.2 47.9 34 48 34 48s21.8-.1 27.1-1.5c2.9-.8 4.6-3.3 5.4-6.2C67.9 35 68 24 68 24s-.1-11-1.5-16.3z" fill="rgba(0,0,0,0.6)"/><path d="M45 24L27 14v20" fill="#fff"/></svg>
        </button>
      </div>`
    : `<div class="card-video card-video-fallback">
        <div class="card-video-placeholder">ARCHIVE</div>
      </div>`;

  return `
    <div class="card" id="card-${index}">
      <div class="card-video-wrap">
        ${youtube}
      </div>
      <div class="card-copy">
        <h3>${displayTitle}</h3>
        ${metaMarkup}
      </div>
    </div>`;
}

function updateCard(index) {
  const ep = allEpisodes[index];
  const card = document.getElementById(`card-${index}`);
  if (!card) return;
  const metaEl = card.querySelector(".card-meta-inline");
  if (ep.date && metaEl) metaEl.textContent = ep.date;
}

function buildDishList(dishes) {
  return dishes.map(d => `<li>${d}</li>`).join("\n        ");
}

function openModal(ep) {
  document.getElementById("modal-title").textContent = normalizeDisplayTitle(ep.title);
  document.getElementById("modal-meta").textContent = ep.date;
  document.getElementById("modal-description").textContent = ep.description || "";
  document.getElementById("modal-overlay").classList.add("open");
}

function closeModal() {
  document.getElementById("modal-overlay").classList.remove("open");
}

function initCarousel(trackEl, dotsEl) {
  let current = 0;
  const total = trackEl.children.length;
  if (total === 0) return;

  const carousel = trackEl.closest(".carousel");
  const prevBtn = carousel.querySelector(".prev-btn");
  const nextBtn = carousel.querySelector(".next-btn");

  // Determine how many cards are visible based on viewport width
  function getVisible() {
    if (window.innerWidth <= 600) return 1;
    if (window.innerWidth <= 800) return 2;
    if (window.innerWidth <= 1100) return 3;
    if (window.innerWidth <= 1400) return 4;
    return 5;
  }

  function getMaxIndex() {
    return Math.max(0, total - getVisible());
  }

  function buildDots() {
    dotsEl.innerHTML = "";
    const maxIdx = getMaxIndex();
    const dotCount = maxIdx + 1;
    for (let i = 0; i < dotCount; i++) {
      const dot = document.createElement("button");
      dot.className = "dot" + (i === current ? " active" : "");
      dot.setAttribute("aria-label", `Slide ${i + 1}`);
      dot.addEventListener("click", () => goTo(i));
      dotsEl.appendChild(dot);
    }
  }

  function goTo(index) {
    const maxIdx = getMaxIndex();
    current = Math.max(0, Math.min(index, maxIdx));
    const offset = trackEl.children[current].offsetLeft;
    trackEl.style.transform = `translateX(-${offset}px)`;
    dotsEl.querySelectorAll(".dot").forEach((d, i) => {
      d.classList.toggle("active", i === current);
    });
    prevBtn.disabled = current === 0;
    nextBtn.disabled = current === maxIdx;
  }

  prevBtn.addEventListener("click", () => goTo(current - 1));
  nextBtn.addEventListener("click", () => goTo(current + 1));

  // Keyboard navigation on the carousel
  carousel.setAttribute("tabindex", "0");
  carousel.addEventListener("keydown", (e) => {
    if (e.key === "ArrowLeft") { goTo(current - 1); e.preventDefault(); }
    if (e.key === "ArrowRight") { goTo(current + 1); e.preventDefault(); }
  });

  buildDots();
  goTo(0);

  // Rebuild dots on resize so visible count stays accurate
  window.addEventListener("resize", () => {
    buildDots();
    goTo(current);
  });
}

async function loadEpisodes() {
  try {
    const res = await fetch("episodes.json");
    if (!res.ok) throw new Error("episodes.json not found");
    const data = await res.json();

    kitchenEpisodes = data.kitchen || [];
    couchEpisodes   = data.couch   || [];

    // Merge in any Spotify IDs configured above
    [...kitchenEpisodes, ...couchEpisodes].forEach(ep => {
      if (ep.youtube && spotifyIds[ep.youtube]) {
        ep.spotify = spotifyIds[ep.youtube];
      }
    });

  } catch (e) {
    console.warn("Could not load episodes.json — using sample episodes.", e);
  }

  // Fall back to sample episodes when none are loaded
  if (kitchenEpisodes.length === 0) kitchenEpisodes = sampleKitchenEpisodes;
  if (couchEpisodes.length === 0)   couchEpisodes   = sampleCouchEpisodes;

  kitchenEpisodes.sort((a, b) => parseEpisodeDate(b.date) - parseEpisodeDate(a.date));
  couchEpisodes.sort((a, b) => parseEpisodeDate(b.date) - parseEpisodeDate(a.date));

  // Rebuild allEpisodes and render
  allEpisodes.length = 0;
  allEpisodes.push(...kitchenEpisodes, ...couchEpisodes);

  const kitchenTrack = document.getElementById("kitchen-track");
  const couchTrack   = document.getElementById("couch-track");

  kitchenTrack.innerHTML = kitchenEpisodes.map((ep, i) => buildCard(ep, i)).join("");
  couchTrack.innerHTML   = couchEpisodes.map((ep, i) => buildCard(ep, kitchenEpisodes.length + i)).join("");
  const dishListEl = document.getElementById("dish-list");
  if (dishListEl) dishListEl.innerHTML = buildDishList(dishes);

  initCarousel(kitchenTrack, document.getElementById("kitchen-dots"));
  initCarousel(couchTrack,   document.getElementById("couch-dots"));
}

document.getElementById("modal-close").addEventListener("click", closeModal);
document.getElementById("modal-overlay").addEventListener("click", function(e) {
  if (e.target === this) closeModal();
});
document.addEventListener("keydown", function(e) {
  if (e.key === "Escape") closeModal();
});
document.addEventListener("click", function(e) {
  if (e.target.classList.contains("read-more")) {
    openModal(allEpisodes[e.target.dataset.index]);
    return;
  }
  const toggleBtn = e.target.closest(".toggle-details");
  if (toggleBtn) {
    const card = toggleBtn.closest(".card");
    card.classList.toggle("details-hidden");
    return;
  }
  const playBtn = e.target.closest(".play-btn");
  if (playBtn) {
    const wrapper = playBtn.closest(".card-video");
    const ytId = wrapper.dataset.yt;
    if (ytId) {
      wrapper.innerHTML = `<iframe src="https://www.youtube.com/embed/${ytId}?autoplay=1" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`;
    }
  }
});

loadEpisodes();

function initRevealAnimations() {
  const reveals = document.querySelectorAll(".reveal");
  if (!reveals.length) return;

  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add("is-visible");
        observer.unobserve(entry.target);
      }
    });
  }, {
    threshold: 0.18,
    rootMargin: "0px 0px -10% 0px",
  });

  reveals.forEach((el) => observer.observe(el));
}

function initLoopingTracks() {
  document.querySelectorAll(".hero-ribbon-track, .blend-band-copy").forEach((track) => {
    if (track.dataset.loopReady === "true") return;
    track.innerHTML += track.innerHTML;
    track.dataset.loopReady = "true";
  });
}

function initHeroTilt() {
  const stage = document.querySelector(".hero-stage");
  if (!stage || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

  stage.addEventListener("pointermove", (event) => {
    const rect = stage.getBoundingClientRect();
    const x = (event.clientX - rect.left) / rect.width;
    const y = (event.clientY - rect.top) / rect.height;
    const rotateY = (x - 0.5) * 8;
    const rotateX = (0.5 - y) * 6;
    stage.style.transform = `perspective(1200px) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`;
  });

  stage.addEventListener("pointerleave", () => {
    stage.style.transform = "";
  });
}

function initHeroSlideshow() {
  const slideshow = document.querySelector("[data-hero-slideshow]");
  if (!slideshow) return;

  const slides = Array.from(slideshow.querySelectorAll(".hero-slide"));
  const dotsWrap = slideshow.querySelector(".hero-slideshow-dots");
  const prevBtn = slideshow.querySelector(".hero-slideshow-arrow-prev");
  const nextBtn = slideshow.querySelector(".hero-slideshow-arrow-next");
  const currentEl = slideshow.querySelector(".hero-slideshow-current");
  const totalEl = slideshow.querySelector(".hero-slideshow-total");
  if (slides.length <= 1 || !dotsWrap || !prevBtn || !nextBtn || !currentEl || !totalEl) return;

  dotsWrap.innerHTML = slides.map((_, index) => (
    `<button class="hero-slideshow-dot${index === 0 ? " is-active" : ""}" type="button" role="tab" aria-selected="${index === 0}" aria-label="Show photo ${index + 1}"></button>`
  )).join("");
  totalEl.textContent = String(slides.length);

  const dots = Array.from(dotsWrap.querySelectorAll(".hero-slideshow-dot"));

  const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  let current = 0;
  let intervalId = null;

  function goTo(index) {
    current = (index + slides.length) % slides.length;
    slides.forEach((slide, slideIndex) => {
      slide.classList.toggle("is-active", slideIndex === current);
    });
    dots.forEach((dot, dotIndex) => {
      const isActive = dotIndex === current;
      dot.classList.toggle("is-active", isActive);
      dot.setAttribute("aria-selected", String(isActive));
    });
    currentEl.textContent = String(current + 1);
  }

  function stopAutoPlay() {
    if (!intervalId) return;
    window.clearInterval(intervalId);
    intervalId = null;
  }

  function startAutoPlay() {
    if (reduceMotion) return;
    stopAutoPlay();
    intervalId = window.setInterval(() => {
      goTo(current + 1);
    }, 4200);
  }

  dots.forEach((dot, index) => {
    dot.addEventListener("click", () => {
      goTo(index);
      startAutoPlay();
    });
  });

  prevBtn.addEventListener("click", () => {
    goTo(current - 1);
    startAutoPlay();
  });

  nextBtn.addEventListener("click", () => {
    goTo(current + 1);
    startAutoPlay();
  });

  slideshow.addEventListener("mouseenter", stopAutoPlay);
  slideshow.addEventListener("mouseleave", startAutoPlay);
  slideshow.addEventListener("focusin", stopAutoPlay);
  slideshow.addEventListener("focusout", startAutoPlay);
  slideshow.addEventListener("keydown", (event) => {
    if (event.key === "ArrowLeft") {
      goTo(current - 1);
      startAutoPlay();
      event.preventDefault();
    }
    if (event.key === "ArrowRight") {
      goTo(current + 1);
      startAutoPlay();
      event.preventDefault();
    }
  });

  goTo(0);
  startAutoPlay();
}

initRevealAnimations();
initLoopingTracks();
initHeroTilt();
initHeroSlideshow();
