// ─────────────────────────────────────────────
//  CONFIGURATION — edit this section only
// ─────────────────────────────────────────────

// Spotify IDs: map YouTube video ID → Spotify episode ID
// When a new episode goes live on Spotify, add its ID here.
//   How to find it: open.spotify.com/episode/EPISODE_ID ← that part
const spotifyIds = {
  // "YOUTUBE_VIDEO_ID": "SPOTIFY_EPISODE_ID",
  // example:
  // "9CoWP2DazGA": "4rOoJ6Egrf8EKCIDo4yj5g",
};

// Dishes cooked — update this list manually
const dishes = [
  "Dish Name One",
  "Dish Name Two",
  "Dish Name Three",
  "Dish Name Four",
  "Dish Name Five",
  "Dish Name Six"
];

// ─────────────────────────────────────────────
//  Episodes are loaded from episodes.json,
//  which is auto-generated by the GitHub Action.
//  You do not need to edit anything below this line.
// ─────────────────────────────────────────────

let kitchenEpisodes = [];
let couchEpisodes   = [];

// ─────────────────────────────────────────────
//  PAGE BUILDER – no need to edit below this line
// ─────────────────────────────────────────────

function validId(id) {
  return id && !id.includes("_ID");
}

const TRUNCATE_LENGTH = 120;

function truncate(text) {
  if (text.length <= TRUNCATE_LENGTH) return { short: text, isTruncated: false };
  return { short: text.slice(0, text.lastIndexOf(" ", TRUNCATE_LENGTH)) + "…", isTruncated: true };
}

// Descriptions are fetched from descriptions.json, which is generated
// automatically by the GitHub Action on every push. No API key needed here.

// All episodes in one flat list so cards can reference them by index
// Populated after episodes.json loads
const allEpisodes = [];

function buildCard(ep, index) {
  const youtube = validId(ep.youtube)
    ? `<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;margin-top:1rem;">
        <iframe
          src="https://www.youtube.com/embed/${ep.youtube}"
          style="position:absolute;top:0;left:0;width:100%;height:100%;"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen
        ></iframe>
      </div>`
    : "";

  const spotify = validId(ep.spotify)
    ? `<iframe
        src="https://open.spotify.com/embed/episode/${ep.spotify}"
        width="100%"
        height="152"
        frameborder="0"
        allowtransparency="true"
        allow="encrypted-media"
        style="margin-top:1rem;border-radius:4px;"
      ></iframe>`
    : "";

  const desc = ep.description || "";
  const { short, isTruncated } = truncate(desc);
  const readMore = isTruncated
    ? `<button class="read-more" data-index="${index}">Read more</button>`
    : "";

  return `
    <div class="card" id="card-${index}">
      <h3>${ep.title}</h3>
      <p class="card-desc">${short}${readMore}</p>
      <div class="ep-meta">${ep.date || ""}</div>
      ${spotify}
      ${youtube}
    </div>`;
}

function updateCard(index) {
  const ep = allEpisodes[index];
  const card = document.getElementById(`card-${index}`);
  if (!card) return;
  const descEl = card.querySelector(".card-desc");
  const { short, isTruncated } = truncate(ep.description || "");
  const readMore = isTruncated
    ? `<button class="read-more" data-index="${index}">Read more</button>`
    : "";
  descEl.innerHTML = short + readMore;
  if (ep.date) card.querySelector(".ep-meta").textContent = ep.date;
}

function buildDishList(dishes) {
  return dishes.map(d => `<li>${d}</li>`).join("\n        ");
}

function openModal(ep) {
  document.getElementById("modal-title").textContent = ep.title;
  document.getElementById("modal-meta").textContent = ep.date;
  document.getElementById("modal-description").textContent = ep.description || "";
  document.getElementById("modal-overlay").classList.add("open");
}

function closeModal() {
  document.getElementById("modal-overlay").classList.remove("open");
}

function initCarousel(trackEl, dotsEl) {
  let current = 0;
  const total = trackEl.children.length;
  if (total === 0) return;

  // Build dots
  for (let i = 0; i < total; i++) {
    const dot = document.createElement("button");
    dot.className = "dot" + (i === 0 ? " active" : "");
    dot.setAttribute("aria-label", `Episode ${i + 1}`);
    dot.addEventListener("click", () => goTo(i));
    dotsEl.appendChild(dot);
  }

  function goTo(index) {
    current = (index + total) % total;
    trackEl.style.transform = `translateX(-${current * 100}%)`;
    dotsEl.querySelectorAll(".dot").forEach((d, i) => {
      d.classList.toggle("active", i === current);
    });
  }

  const carousel = trackEl.closest(".carousel");
  carousel.querySelector(".prev-btn").addEventListener("click", () => goTo(current - 1));
  carousel.querySelector(".next-btn").addEventListener("click", () => goTo(current + 1));
}

async function loadEpisodes() {
  try {
    const res = await fetch("episodes.json");
    if (!res.ok) throw new Error("episodes.json not found");
    const data = await res.json();

    kitchenEpisodes = data.kitchen || [];
    couchEpisodes   = data.couch   || [];

    // Merge in any Spotify IDs configured above
    [...kitchenEpisodes, ...couchEpisodes].forEach(ep => {
      if (ep.youtube && spotifyIds[ep.youtube]) {
        ep.spotify = spotifyIds[ep.youtube];
      }
    });

  } catch (e) {
    console.warn("Could not load episodes.json — page may be empty.", e);
  }

  // Rebuild allEpisodes and render
  allEpisodes.length = 0;
  allEpisodes.push(...kitchenEpisodes, ...couchEpisodes);

  const kitchenTrack = document.getElementById("kitchen-track");
  const couchTrack   = document.getElementById("couch-track");

  kitchenTrack.innerHTML = kitchenEpisodes.map(buildCard).join("");
  couchTrack.innerHTML   = couchEpisodes.map((ep, i) => buildCard(ep, kitchenEpisodes.length + i)).join("");
  document.getElementById("dish-list").innerHTML = buildDishList(dishes);

  initCarousel(kitchenTrack, document.getElementById("kitchen-dots"));
  initCarousel(couchTrack,   document.getElementById("couch-dots"));
}

document.getElementById("modal-close").addEventListener("click", closeModal);
document.getElementById("modal-overlay").addEventListener("click", function(e) {
  if (e.target === this) closeModal();
});
document.addEventListener("keydown", function(e) {
  if (e.key === "Escape") closeModal();
});
document.addEventListener("click", function(e) {
  if (e.target.classList.contains("read-more")) {
    openModal(allEpisodes[e.target.dataset.index]);
  }
});

loadEpisodes();
